email_sorter:
  description: >
    Go through ten most recent of emails in users' inbox and classify them into three buckets - the ones which
    require immediate attention, second which needs to be visited when time permits, and finally
    the ones which can be ignored with no consequences whatsoever.
  expected_output: >
    A sorted list of three buckets of output - High, Medium and Low, alias Urgent, Noble and Common
  agent: mail_assistant

